### ISSUE TITLE
Issue with Model Initialization in Explainer Method

### ISSUE THREAD

**Issue by Andy-Mielk** [fuxiAIlab/xrl-bench#1]
Hi, thanks for your work. I am an XRL beginner and have been trying to execute the example code provided in your repository.
However, I encountered an error that I believe might be related to the code itself. The error message I received is as follows:
TypeError: The passed model is not callable and cannot be analyzed directly with the given masker! Model: LGBMClassifier().

I am wondering if there might be an issue with the latest version of the code. Could you please provide some guidance on how to address these errors? Your assistance would be greatly appreciated.

Thank you very much for your time and support.

**Comment by yuxiong0521** [comment]
> Hi, thanks for your work. I am an XRL beginner and have been trying to execute the example code provided in your repository. However, I encountered an error that I believe might be related to the code itself. The error message I received is as follows: TypeError: The passed model is not callable and cannot be analyzed directly with the given masker! Model: LGBMClassifier().
> 
> I am wondering if there might be an issue with the latest version of the code. Could you please provide some guidance on how to address these errors? Your assistance would be greatly appreciated.
> 
> Thank you very much for your time and support.

The issue has been fixed. Please update your code to the latest version and run it again.
